
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SharedUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SharedUser
 * 
 */
export type SharedUserModel = runtime.Types.Result.DefaultSelection<Prisma.$SharedUserPayload>

export type AggregateSharedUser = {
  _count: SharedUserCountAggregateOutputType | null
  _avg: SharedUserAvgAggregateOutputType | null
  _sum: SharedUserSumAggregateOutputType | null
  _min: SharedUserMinAggregateOutputType | null
  _max: SharedUserMaxAggregateOutputType | null
}

export type SharedUserAvgAggregateOutputType = {
  fluencyScore: number | null
  englivoCredits: number | null
}

export type SharedUserSumAggregateOutputType = {
  fluencyScore: number | null
  englivoCredits: number | null
}

export type SharedUserMinAggregateOutputType = {
  clerkId: string | null
  email: string | null
  fullName: string | null
  cefrLevel: string | null
  fluencyScore: number | null
  cefrUpdatedAt: Date | null
  cefrUpdatedBy: string | null
  englivoPlan: string | null
  engrPlan: string | null
  englivoCredits: number | null
  englivoProvisioned: boolean | null
  engrProvisioned: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SharedUserMaxAggregateOutputType = {
  clerkId: string | null
  email: string | null
  fullName: string | null
  cefrLevel: string | null
  fluencyScore: number | null
  cefrUpdatedAt: Date | null
  cefrUpdatedBy: string | null
  englivoPlan: string | null
  engrPlan: string | null
  englivoCredits: number | null
  englivoProvisioned: boolean | null
  engrProvisioned: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SharedUserCountAggregateOutputType = {
  clerkId: number
  email: number
  fullName: number
  cefrLevel: number
  fluencyScore: number
  cefrUpdatedAt: number
  cefrUpdatedBy: number
  englivoPlan: number
  engrPlan: number
  englivoCredits: number
  englivoProvisioned: number
  engrProvisioned: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SharedUserAvgAggregateInputType = {
  fluencyScore?: true
  englivoCredits?: true
}

export type SharedUserSumAggregateInputType = {
  fluencyScore?: true
  englivoCredits?: true
}

export type SharedUserMinAggregateInputType = {
  clerkId?: true
  email?: true
  fullName?: true
  cefrLevel?: true
  fluencyScore?: true
  cefrUpdatedAt?: true
  cefrUpdatedBy?: true
  englivoPlan?: true
  engrPlan?: true
  englivoCredits?: true
  englivoProvisioned?: true
  engrProvisioned?: true
  createdAt?: true
  updatedAt?: true
}

export type SharedUserMaxAggregateInputType = {
  clerkId?: true
  email?: true
  fullName?: true
  cefrLevel?: true
  fluencyScore?: true
  cefrUpdatedAt?: true
  cefrUpdatedBy?: true
  englivoPlan?: true
  engrPlan?: true
  englivoCredits?: true
  englivoProvisioned?: true
  engrProvisioned?: true
  createdAt?: true
  updatedAt?: true
}

export type SharedUserCountAggregateInputType = {
  clerkId?: true
  email?: true
  fullName?: true
  cefrLevel?: true
  fluencyScore?: true
  cefrUpdatedAt?: true
  cefrUpdatedBy?: true
  englivoPlan?: true
  engrPlan?: true
  englivoCredits?: true
  englivoProvisioned?: true
  engrProvisioned?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SharedUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SharedUser to aggregate.
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SharedUsers to fetch.
   */
  orderBy?: Prisma.SharedUserOrderByWithRelationInput | Prisma.SharedUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SharedUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SharedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SharedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SharedUsers
  **/
  _count?: true | SharedUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SharedUserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SharedUserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SharedUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SharedUserMaxAggregateInputType
}

export type GetSharedUserAggregateType<T extends SharedUserAggregateArgs> = {
      [P in keyof T & keyof AggregateSharedUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSharedUser[P]>
    : Prisma.GetScalarType<T[P], AggregateSharedUser[P]>
}




export type SharedUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SharedUserWhereInput
  orderBy?: Prisma.SharedUserOrderByWithAggregationInput | Prisma.SharedUserOrderByWithAggregationInput[]
  by: Prisma.SharedUserScalarFieldEnum[] | Prisma.SharedUserScalarFieldEnum
  having?: Prisma.SharedUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SharedUserCountAggregateInputType | true
  _avg?: SharedUserAvgAggregateInputType
  _sum?: SharedUserSumAggregateInputType
  _min?: SharedUserMinAggregateInputType
  _max?: SharedUserMaxAggregateInputType
}

export type SharedUserGroupByOutputType = {
  clerkId: string
  email: string
  fullName: string
  cefrLevel: string
  fluencyScore: number
  cefrUpdatedAt: Date
  cefrUpdatedBy: string | null
  englivoPlan: string
  engrPlan: string
  englivoCredits: number
  englivoProvisioned: boolean
  engrProvisioned: boolean
  createdAt: Date
  updatedAt: Date
  _count: SharedUserCountAggregateOutputType | null
  _avg: SharedUserAvgAggregateOutputType | null
  _sum: SharedUserSumAggregateOutputType | null
  _min: SharedUserMinAggregateOutputType | null
  _max: SharedUserMaxAggregateOutputType | null
}

type GetSharedUserGroupByPayload<T extends SharedUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SharedUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SharedUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SharedUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SharedUserGroupByOutputType[P]>
      }
    >
  >



export type SharedUserWhereInput = {
  AND?: Prisma.SharedUserWhereInput | Prisma.SharedUserWhereInput[]
  OR?: Prisma.SharedUserWhereInput[]
  NOT?: Prisma.SharedUserWhereInput | Prisma.SharedUserWhereInput[]
  clerkId?: Prisma.StringFilter<"SharedUser"> | string
  email?: Prisma.StringFilter<"SharedUser"> | string
  fullName?: Prisma.StringFilter<"SharedUser"> | string
  cefrLevel?: Prisma.StringFilter<"SharedUser"> | string
  fluencyScore?: Prisma.FloatFilter<"SharedUser"> | number
  cefrUpdatedAt?: Prisma.DateTimeFilter<"SharedUser"> | Date | string
  cefrUpdatedBy?: Prisma.StringNullableFilter<"SharedUser"> | string | null
  englivoPlan?: Prisma.StringFilter<"SharedUser"> | string
  engrPlan?: Prisma.StringFilter<"SharedUser"> | string
  englivoCredits?: Prisma.IntFilter<"SharedUser"> | number
  englivoProvisioned?: Prisma.BoolFilter<"SharedUser"> | boolean
  engrProvisioned?: Prisma.BoolFilter<"SharedUser"> | boolean
  createdAt?: Prisma.DateTimeFilter<"SharedUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SharedUser"> | Date | string
}

export type SharedUserOrderByWithRelationInput = {
  clerkId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  cefrLevel?: Prisma.SortOrder
  fluencyScore?: Prisma.SortOrder
  cefrUpdatedAt?: Prisma.SortOrder
  cefrUpdatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  englivoPlan?: Prisma.SortOrder
  engrPlan?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
  englivoProvisioned?: Prisma.SortOrder
  engrProvisioned?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SharedUserWhereUniqueInput = Prisma.AtLeast<{
  clerkId?: string
  email?: string
  AND?: Prisma.SharedUserWhereInput | Prisma.SharedUserWhereInput[]
  OR?: Prisma.SharedUserWhereInput[]
  NOT?: Prisma.SharedUserWhereInput | Prisma.SharedUserWhereInput[]
  fullName?: Prisma.StringFilter<"SharedUser"> | string
  cefrLevel?: Prisma.StringFilter<"SharedUser"> | string
  fluencyScore?: Prisma.FloatFilter<"SharedUser"> | number
  cefrUpdatedAt?: Prisma.DateTimeFilter<"SharedUser"> | Date | string
  cefrUpdatedBy?: Prisma.StringNullableFilter<"SharedUser"> | string | null
  englivoPlan?: Prisma.StringFilter<"SharedUser"> | string
  engrPlan?: Prisma.StringFilter<"SharedUser"> | string
  englivoCredits?: Prisma.IntFilter<"SharedUser"> | number
  englivoProvisioned?: Prisma.BoolFilter<"SharedUser"> | boolean
  engrProvisioned?: Prisma.BoolFilter<"SharedUser"> | boolean
  createdAt?: Prisma.DateTimeFilter<"SharedUser"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SharedUser"> | Date | string
}, "clerkId" | "email">

export type SharedUserOrderByWithAggregationInput = {
  clerkId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  cefrLevel?: Prisma.SortOrder
  fluencyScore?: Prisma.SortOrder
  cefrUpdatedAt?: Prisma.SortOrder
  cefrUpdatedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  englivoPlan?: Prisma.SortOrder
  engrPlan?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
  englivoProvisioned?: Prisma.SortOrder
  engrProvisioned?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SharedUserCountOrderByAggregateInput
  _avg?: Prisma.SharedUserAvgOrderByAggregateInput
  _max?: Prisma.SharedUserMaxOrderByAggregateInput
  _min?: Prisma.SharedUserMinOrderByAggregateInput
  _sum?: Prisma.SharedUserSumOrderByAggregateInput
}

export type SharedUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.SharedUserScalarWhereWithAggregatesInput | Prisma.SharedUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.SharedUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SharedUserScalarWhereWithAggregatesInput | Prisma.SharedUserScalarWhereWithAggregatesInput[]
  clerkId?: Prisma.StringWithAggregatesFilter<"SharedUser"> | string
  email?: Prisma.StringWithAggregatesFilter<"SharedUser"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"SharedUser"> | string
  cefrLevel?: Prisma.StringWithAggregatesFilter<"SharedUser"> | string
  fluencyScore?: Prisma.FloatWithAggregatesFilter<"SharedUser"> | number
  cefrUpdatedAt?: Prisma.DateTimeWithAggregatesFilter<"SharedUser"> | Date | string
  cefrUpdatedBy?: Prisma.StringNullableWithAggregatesFilter<"SharedUser"> | string | null
  englivoPlan?: Prisma.StringWithAggregatesFilter<"SharedUser"> | string
  engrPlan?: Prisma.StringWithAggregatesFilter<"SharedUser"> | string
  englivoCredits?: Prisma.IntWithAggregatesFilter<"SharedUser"> | number
  englivoProvisioned?: Prisma.BoolWithAggregatesFilter<"SharedUser"> | boolean
  engrProvisioned?: Prisma.BoolWithAggregatesFilter<"SharedUser"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SharedUser"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SharedUser"> | Date | string
}

export type SharedUserCreateInput = {
  clerkId: string
  email: string
  fullName: string
  cefrLevel?: string
  fluencyScore?: number
  cefrUpdatedAt?: Date | string
  cefrUpdatedBy?: string | null
  englivoPlan?: string
  engrPlan?: string
  englivoCredits?: number
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SharedUserUncheckedCreateInput = {
  clerkId: string
  email: string
  fullName: string
  cefrLevel?: string
  fluencyScore?: number
  cefrUpdatedAt?: Date | string
  cefrUpdatedBy?: string | null
  englivoPlan?: string
  engrPlan?: string
  englivoCredits?: number
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SharedUserUpdateInput = {
  clerkId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  cefrLevel?: Prisma.StringFieldUpdateOperationsInput | string
  fluencyScore?: Prisma.FloatFieldUpdateOperationsInput | number
  cefrUpdatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cefrUpdatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  englivoPlan?: Prisma.StringFieldUpdateOperationsInput | string
  engrPlan?: Prisma.StringFieldUpdateOperationsInput | string
  englivoCredits?: Prisma.IntFieldUpdateOperationsInput | number
  englivoProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  engrProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SharedUserUncheckedUpdateInput = {
  clerkId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  cefrLevel?: Prisma.StringFieldUpdateOperationsInput | string
  fluencyScore?: Prisma.FloatFieldUpdateOperationsInput | number
  cefrUpdatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cefrUpdatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  englivoPlan?: Prisma.StringFieldUpdateOperationsInput | string
  engrPlan?: Prisma.StringFieldUpdateOperationsInput | string
  englivoCredits?: Prisma.IntFieldUpdateOperationsInput | number
  englivoProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  engrProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SharedUserCreateManyInput = {
  clerkId: string
  email: string
  fullName: string
  cefrLevel?: string
  fluencyScore?: number
  cefrUpdatedAt?: Date | string
  cefrUpdatedBy?: string | null
  englivoPlan?: string
  engrPlan?: string
  englivoCredits?: number
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SharedUserUpdateManyMutationInput = {
  clerkId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  cefrLevel?: Prisma.StringFieldUpdateOperationsInput | string
  fluencyScore?: Prisma.FloatFieldUpdateOperationsInput | number
  cefrUpdatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cefrUpdatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  englivoPlan?: Prisma.StringFieldUpdateOperationsInput | string
  engrPlan?: Prisma.StringFieldUpdateOperationsInput | string
  englivoCredits?: Prisma.IntFieldUpdateOperationsInput | number
  englivoProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  engrProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SharedUserUncheckedUpdateManyInput = {
  clerkId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  cefrLevel?: Prisma.StringFieldUpdateOperationsInput | string
  fluencyScore?: Prisma.FloatFieldUpdateOperationsInput | number
  cefrUpdatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cefrUpdatedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  englivoPlan?: Prisma.StringFieldUpdateOperationsInput | string
  engrPlan?: Prisma.StringFieldUpdateOperationsInput | string
  englivoCredits?: Prisma.IntFieldUpdateOperationsInput | number
  englivoProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  engrProvisioned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SharedUserCountOrderByAggregateInput = {
  clerkId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  cefrLevel?: Prisma.SortOrder
  fluencyScore?: Prisma.SortOrder
  cefrUpdatedAt?: Prisma.SortOrder
  cefrUpdatedBy?: Prisma.SortOrder
  englivoPlan?: Prisma.SortOrder
  engrPlan?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
  englivoProvisioned?: Prisma.SortOrder
  engrProvisioned?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SharedUserAvgOrderByAggregateInput = {
  fluencyScore?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
}

export type SharedUserMaxOrderByAggregateInput = {
  clerkId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  cefrLevel?: Prisma.SortOrder
  fluencyScore?: Prisma.SortOrder
  cefrUpdatedAt?: Prisma.SortOrder
  cefrUpdatedBy?: Prisma.SortOrder
  englivoPlan?: Prisma.SortOrder
  engrPlan?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
  englivoProvisioned?: Prisma.SortOrder
  engrProvisioned?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SharedUserMinOrderByAggregateInput = {
  clerkId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  cefrLevel?: Prisma.SortOrder
  fluencyScore?: Prisma.SortOrder
  cefrUpdatedAt?: Prisma.SortOrder
  cefrUpdatedBy?: Prisma.SortOrder
  englivoPlan?: Prisma.SortOrder
  engrPlan?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
  englivoProvisioned?: Prisma.SortOrder
  engrProvisioned?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SharedUserSumOrderByAggregateInput = {
  fluencyScore?: Prisma.SortOrder
  englivoCredits?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type SharedUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  clerkId?: boolean
  email?: boolean
  fullName?: boolean
  cefrLevel?: boolean
  fluencyScore?: boolean
  cefrUpdatedAt?: boolean
  cefrUpdatedBy?: boolean
  englivoPlan?: boolean
  engrPlan?: boolean
  englivoCredits?: boolean
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sharedUser"]>

export type SharedUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  clerkId?: boolean
  email?: boolean
  fullName?: boolean
  cefrLevel?: boolean
  fluencyScore?: boolean
  cefrUpdatedAt?: boolean
  cefrUpdatedBy?: boolean
  englivoPlan?: boolean
  engrPlan?: boolean
  englivoCredits?: boolean
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sharedUser"]>

export type SharedUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  clerkId?: boolean
  email?: boolean
  fullName?: boolean
  cefrLevel?: boolean
  fluencyScore?: boolean
  cefrUpdatedAt?: boolean
  cefrUpdatedBy?: boolean
  englivoPlan?: boolean
  engrPlan?: boolean
  englivoCredits?: boolean
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sharedUser"]>

export type SharedUserSelectScalar = {
  clerkId?: boolean
  email?: boolean
  fullName?: boolean
  cefrLevel?: boolean
  fluencyScore?: boolean
  cefrUpdatedAt?: boolean
  cefrUpdatedBy?: boolean
  englivoPlan?: boolean
  engrPlan?: boolean
  englivoCredits?: boolean
  englivoProvisioned?: boolean
  engrProvisioned?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SharedUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"clerkId" | "email" | "fullName" | "cefrLevel" | "fluencyScore" | "cefrUpdatedAt" | "cefrUpdatedBy" | "englivoPlan" | "engrPlan" | "englivoCredits" | "englivoProvisioned" | "engrProvisioned" | "createdAt" | "updatedAt", ExtArgs["result"]["sharedUser"]>

export type $SharedUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SharedUser"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    clerkId: string
    email: string
    fullName: string
    cefrLevel: string
    fluencyScore: number
    cefrUpdatedAt: Date
    cefrUpdatedBy: string | null
    englivoPlan: string
    engrPlan: string
    englivoCredits: number
    englivoProvisioned: boolean
    engrProvisioned: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sharedUser"]>
  composites: {}
}

export type SharedUserGetPayload<S extends boolean | null | undefined | SharedUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SharedUserPayload, S>

export type SharedUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SharedUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SharedUserCountAggregateInputType | true
  }

export interface SharedUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SharedUser'], meta: { name: 'SharedUser' } }
  /**
   * Find zero or one SharedUser that matches the filter.
   * @param {SharedUserFindUniqueArgs} args - Arguments to find a SharedUser
   * @example
   * // Get one SharedUser
   * const sharedUser = await prisma.sharedUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SharedUserFindUniqueArgs>(args: Prisma.SelectSubset<T, SharedUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SharedUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SharedUserFindUniqueOrThrowArgs} args - Arguments to find a SharedUser
   * @example
   * // Get one SharedUser
   * const sharedUser = await prisma.sharedUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SharedUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SharedUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SharedUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserFindFirstArgs} args - Arguments to find a SharedUser
   * @example
   * // Get one SharedUser
   * const sharedUser = await prisma.sharedUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SharedUserFindFirstArgs>(args?: Prisma.SelectSubset<T, SharedUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SharedUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserFindFirstOrThrowArgs} args - Arguments to find a SharedUser
   * @example
   * // Get one SharedUser
   * const sharedUser = await prisma.sharedUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SharedUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SharedUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SharedUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SharedUsers
   * const sharedUsers = await prisma.sharedUser.findMany()
   * 
   * // Get first 10 SharedUsers
   * const sharedUsers = await prisma.sharedUser.findMany({ take: 10 })
   * 
   * // Only select the `clerkId`
   * const sharedUserWithClerkIdOnly = await prisma.sharedUser.findMany({ select: { clerkId: true } })
   * 
   */
  findMany<T extends SharedUserFindManyArgs>(args?: Prisma.SelectSubset<T, SharedUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SharedUser.
   * @param {SharedUserCreateArgs} args - Arguments to create a SharedUser.
   * @example
   * // Create one SharedUser
   * const SharedUser = await prisma.sharedUser.create({
   *   data: {
   *     // ... data to create a SharedUser
   *   }
   * })
   * 
   */
  create<T extends SharedUserCreateArgs>(args: Prisma.SelectSubset<T, SharedUserCreateArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SharedUsers.
   * @param {SharedUserCreateManyArgs} args - Arguments to create many SharedUsers.
   * @example
   * // Create many SharedUsers
   * const sharedUser = await prisma.sharedUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SharedUserCreateManyArgs>(args?: Prisma.SelectSubset<T, SharedUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SharedUsers and returns the data saved in the database.
   * @param {SharedUserCreateManyAndReturnArgs} args - Arguments to create many SharedUsers.
   * @example
   * // Create many SharedUsers
   * const sharedUser = await prisma.sharedUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SharedUsers and only return the `clerkId`
   * const sharedUserWithClerkIdOnly = await prisma.sharedUser.createManyAndReturn({
   *   select: { clerkId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SharedUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SharedUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SharedUser.
   * @param {SharedUserDeleteArgs} args - Arguments to delete one SharedUser.
   * @example
   * // Delete one SharedUser
   * const SharedUser = await prisma.sharedUser.delete({
   *   where: {
   *     // ... filter to delete one SharedUser
   *   }
   * })
   * 
   */
  delete<T extends SharedUserDeleteArgs>(args: Prisma.SelectSubset<T, SharedUserDeleteArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SharedUser.
   * @param {SharedUserUpdateArgs} args - Arguments to update one SharedUser.
   * @example
   * // Update one SharedUser
   * const sharedUser = await prisma.sharedUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SharedUserUpdateArgs>(args: Prisma.SelectSubset<T, SharedUserUpdateArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SharedUsers.
   * @param {SharedUserDeleteManyArgs} args - Arguments to filter SharedUsers to delete.
   * @example
   * // Delete a few SharedUsers
   * const { count } = await prisma.sharedUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SharedUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, SharedUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SharedUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SharedUsers
   * const sharedUser = await prisma.sharedUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SharedUserUpdateManyArgs>(args: Prisma.SelectSubset<T, SharedUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SharedUsers and returns the data updated in the database.
   * @param {SharedUserUpdateManyAndReturnArgs} args - Arguments to update many SharedUsers.
   * @example
   * // Update many SharedUsers
   * const sharedUser = await prisma.sharedUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SharedUsers and only return the `clerkId`
   * const sharedUserWithClerkIdOnly = await prisma.sharedUser.updateManyAndReturn({
   *   select: { clerkId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SharedUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SharedUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SharedUser.
   * @param {SharedUserUpsertArgs} args - Arguments to update or create a SharedUser.
   * @example
   * // Update or create a SharedUser
   * const sharedUser = await prisma.sharedUser.upsert({
   *   create: {
   *     // ... data to create a SharedUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SharedUser we want to update
   *   }
   * })
   */
  upsert<T extends SharedUserUpsertArgs>(args: Prisma.SelectSubset<T, SharedUserUpsertArgs<ExtArgs>>): Prisma.Prisma__SharedUserClient<runtime.Types.Result.GetResult<Prisma.$SharedUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SharedUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserCountArgs} args - Arguments to filter SharedUsers to count.
   * @example
   * // Count the number of SharedUsers
   * const count = await prisma.sharedUser.count({
   *   where: {
   *     // ... the filter for the SharedUsers we want to count
   *   }
   * })
  **/
  count<T extends SharedUserCountArgs>(
    args?: Prisma.Subset<T, SharedUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SharedUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SharedUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SharedUserAggregateArgs>(args: Prisma.Subset<T, SharedUserAggregateArgs>): Prisma.PrismaPromise<GetSharedUserAggregateType<T>>

  /**
   * Group by SharedUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SharedUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SharedUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SharedUserGroupByArgs['orderBy'] }
      : { orderBy?: SharedUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SharedUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSharedUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SharedUser model
 */
readonly fields: SharedUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SharedUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SharedUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SharedUser model
 */
export interface SharedUserFieldRefs {
  readonly clerkId: Prisma.FieldRef<"SharedUser", 'String'>
  readonly email: Prisma.FieldRef<"SharedUser", 'String'>
  readonly fullName: Prisma.FieldRef<"SharedUser", 'String'>
  readonly cefrLevel: Prisma.FieldRef<"SharedUser", 'String'>
  readonly fluencyScore: Prisma.FieldRef<"SharedUser", 'Float'>
  readonly cefrUpdatedAt: Prisma.FieldRef<"SharedUser", 'DateTime'>
  readonly cefrUpdatedBy: Prisma.FieldRef<"SharedUser", 'String'>
  readonly englivoPlan: Prisma.FieldRef<"SharedUser", 'String'>
  readonly engrPlan: Prisma.FieldRef<"SharedUser", 'String'>
  readonly englivoCredits: Prisma.FieldRef<"SharedUser", 'Int'>
  readonly englivoProvisioned: Prisma.FieldRef<"SharedUser", 'Boolean'>
  readonly engrProvisioned: Prisma.FieldRef<"SharedUser", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"SharedUser", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SharedUser", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SharedUser findUnique
 */
export type SharedUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * Filter, which SharedUser to fetch.
   */
  where: Prisma.SharedUserWhereUniqueInput
}

/**
 * SharedUser findUniqueOrThrow
 */
export type SharedUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * Filter, which SharedUser to fetch.
   */
  where: Prisma.SharedUserWhereUniqueInput
}

/**
 * SharedUser findFirst
 */
export type SharedUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * Filter, which SharedUser to fetch.
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SharedUsers to fetch.
   */
  orderBy?: Prisma.SharedUserOrderByWithRelationInput | Prisma.SharedUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SharedUsers.
   */
  cursor?: Prisma.SharedUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SharedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SharedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SharedUsers.
   */
  distinct?: Prisma.SharedUserScalarFieldEnum | Prisma.SharedUserScalarFieldEnum[]
}

/**
 * SharedUser findFirstOrThrow
 */
export type SharedUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * Filter, which SharedUser to fetch.
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SharedUsers to fetch.
   */
  orderBy?: Prisma.SharedUserOrderByWithRelationInput | Prisma.SharedUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SharedUsers.
   */
  cursor?: Prisma.SharedUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SharedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SharedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SharedUsers.
   */
  distinct?: Prisma.SharedUserScalarFieldEnum | Prisma.SharedUserScalarFieldEnum[]
}

/**
 * SharedUser findMany
 */
export type SharedUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * Filter, which SharedUsers to fetch.
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SharedUsers to fetch.
   */
  orderBy?: Prisma.SharedUserOrderByWithRelationInput | Prisma.SharedUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SharedUsers.
   */
  cursor?: Prisma.SharedUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SharedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SharedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SharedUsers.
   */
  distinct?: Prisma.SharedUserScalarFieldEnum | Prisma.SharedUserScalarFieldEnum[]
}

/**
 * SharedUser create
 */
export type SharedUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * The data needed to create a SharedUser.
   */
  data: Prisma.XOR<Prisma.SharedUserCreateInput, Prisma.SharedUserUncheckedCreateInput>
}

/**
 * SharedUser createMany
 */
export type SharedUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SharedUsers.
   */
  data: Prisma.SharedUserCreateManyInput | Prisma.SharedUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SharedUser createManyAndReturn
 */
export type SharedUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * The data used to create many SharedUsers.
   */
  data: Prisma.SharedUserCreateManyInput | Prisma.SharedUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SharedUser update
 */
export type SharedUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * The data needed to update a SharedUser.
   */
  data: Prisma.XOR<Prisma.SharedUserUpdateInput, Prisma.SharedUserUncheckedUpdateInput>
  /**
   * Choose, which SharedUser to update.
   */
  where: Prisma.SharedUserWhereUniqueInput
}

/**
 * SharedUser updateMany
 */
export type SharedUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SharedUsers.
   */
  data: Prisma.XOR<Prisma.SharedUserUpdateManyMutationInput, Prisma.SharedUserUncheckedUpdateManyInput>
  /**
   * Filter which SharedUsers to update
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * Limit how many SharedUsers to update.
   */
  limit?: number
}

/**
 * SharedUser updateManyAndReturn
 */
export type SharedUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * The data used to update SharedUsers.
   */
  data: Prisma.XOR<Prisma.SharedUserUpdateManyMutationInput, Prisma.SharedUserUncheckedUpdateManyInput>
  /**
   * Filter which SharedUsers to update
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * Limit how many SharedUsers to update.
   */
  limit?: number
}

/**
 * SharedUser upsert
 */
export type SharedUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * The filter to search for the SharedUser to update in case it exists.
   */
  where: Prisma.SharedUserWhereUniqueInput
  /**
   * In case the SharedUser found by the `where` argument doesn't exist, create a new SharedUser with this data.
   */
  create: Prisma.XOR<Prisma.SharedUserCreateInput, Prisma.SharedUserUncheckedCreateInput>
  /**
   * In case the SharedUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SharedUserUpdateInput, Prisma.SharedUserUncheckedUpdateInput>
}

/**
 * SharedUser delete
 */
export type SharedUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
  /**
   * Filter which SharedUser to delete.
   */
  where: Prisma.SharedUserWhereUniqueInput
}

/**
 * SharedUser deleteMany
 */
export type SharedUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SharedUsers to delete
   */
  where?: Prisma.SharedUserWhereInput
  /**
   * Limit how many SharedUsers to delete.
   */
  limit?: number
}

/**
 * SharedUser without action
 */
export type SharedUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SharedUser
   */
  select?: Prisma.SharedUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SharedUser
   */
  omit?: Prisma.SharedUserOmit<ExtArgs> | null
}
