/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck

/*
 * This file should be your main import to use Prisma. Through it you get access to all models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

const { PrismaClient } = $Class.getPrismaClientClass()

module.exports = {
  PrismaClient,
  Prisma,
  $Enums,
  ...require('./browser'),
}
